name = "agenbrilink"
compatibility_date = "2026-06-16"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "agenbrilink_db"
database_id = "348e4718-dc1e-4cca-9e8f-59d1d6ab0f5e"
